-- MySQL Script generated by MySQL Workbench
-- Wed May 29 12:29:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_inventario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistema_inventario` ;

-- -----------------------------------------------------
-- Table `sistema_inventario`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`cargos` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT '1',
  `salario` DECIMAL(10,2) NOT NULL,
  `id_cargo` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE,
  INDEX `fk_empleado_cargo_idx` (`id_cargo` ASC) VISIBLE,
  INDEX `fk_empleado_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_cargo`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `sistema_inventario`.`cargos` (`id_cargo`),
  CONSTRAINT `fk_empleado_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_inventario`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`bodegas` (
  `id_bodega` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `encargado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_bodega`),
  INDEX `fk_encargado_empleado_idx` (`encargado` ASC) VISIBLE,
  CONSTRAINT `fk_encargado_empleado`
    FOREIGN KEY (`encargado`)
    REFERENCES `sistema_inventario`.`empleados` (`id_empleado`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE,
  INDEX `fk_proveedor_persona_idx` (`id_proveedor` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`empresas` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `codigo_empresa` VARCHAR(100) NOT NULL,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `telefono_empresa` VARCHAR(100) NOT NULL,
  `direccion_empresa` VARCHAR(100) NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `codigo_empresa_UNIQUE` (`codigo_empresa` ASC) VISIBLE,
  INDEX `fk_empresa_proveedor_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `sistema_inventario`.`proveedores` (`id_proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `precio_compra` DECIMAL(10,2) NULL DEFAULT NULL,
  `precio_venta` DECIMAL(10,0) NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `referencia_UNIQUE` (`referencia` ASC) VISIBLE,
  INDEX `fk_producto_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `sistema_inventario`.`categorias` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`puntos_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`puntos_ventas` (
  `id_puntos_venta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `encargado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_puntos_venta`),
  INDEX `fk_encargado_empleado_idx` (`encargado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`seguimientos_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`seguimientos_productos` (
  `id_seguimientos_productos` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_bodega` INT NOT NULL,
  `id_punto_venta` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_seguimientos_productos`),
  INDEX `fk_seguimiento_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_seguimiento_bodega_idx` (`id_bodega` ASC) VISIBLE,
  INDEX `fk_seguimiento_punto_venta_idx` (`id_punto_venta` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_bodega`
    FOREIGN KEY (`id_bodega`)
    REFERENCES `sistema_inventario`.`bodegas` (`id_bodega`),
  CONSTRAINT `fk_seguimiento_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `sistema_inventario`.`productos` (`id_producto`),
  CONSTRAINT `fk_seguimiento_punto_venta`
    FOREIGN KEY (`id_punto_venta`)
    REFERENCES `sistema_inventario`.`puntos_ventas` (`id_puntos_venta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
