-- MySQL Script generated by MySQL Workbench
-- Wed May 22 09:33:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventario_sena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario_sena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario_sena` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inventario_sena` ;

-- -----------------------------------------------------
-- Table `inventario_sena`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(10) NULL DEFAULT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `fecha_ingreso` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` VARCHAR(20) NOT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE,
  INDEX `fk_roles_idx` (`cargo` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `inventario_sena`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 185
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`bodegas` (
  `id_bodega` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `encargado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_bodega`),
  INDEX `fk_encargado_idx` (`encargado` ASC) VISIBLE,
  CONSTRAINT `fk_encargado`
    FOREIGN KEY (`encargado`)
    REFERENCES `inventario_sena`.`empleados` (`id_empleado`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`proveedores` (
  `id_proveedores` INT NOT NULL AUTO_INCREMENT,
  `nit` INT NOT NULL,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_proveedores`),
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`puntos_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`puntos_venta` (
  `id_punto_venta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `encargado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_punto_venta`),
  INDEX `fk_encargado_punto_venta_idx` (`encargado` ASC) VISIBLE,
  CONSTRAINT `fk_encargado_punto_venta`
    FOREIGN KEY (`encargado`)
    REFERENCES `inventario_sena`.`empleados` (`id_empleado`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`ubicacion_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`ubicacion_productos` (
  `id_ubicacion` INT NOT NULL AUTO_INCREMENT,
  `bodega_ubicacon` INT NULL DEFAULT NULL,
  `punto_venta_ubicacion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ubicacion`),
  INDEX `fk_ubicacion_bodega_idx` (`bodega_ubicacon` ASC) VISIBLE,
  INDEX `fk_punto_venta_ubicacion_idx` (`punto_venta_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_bodega_ubicacion`
    FOREIGN KEY (`bodega_ubicacon`)
    REFERENCES `inventario_sena`.`bodegas` (`id_bodega`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_punto_venta_ubicacion`
    FOREIGN KEY (`punto_venta_ubicacion`)
    REFERENCES `inventario_sena`.`puntos_venta` (`id_punto_venta`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `referencia` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `precio_compra` DECIMAL(10,2) NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `agregado_por` INT NULL DEFAULT NULL,
  `proveedor` INT NULL DEFAULT NULL,
  `ubicado_en` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `referencia_UNIQUE` (`referencia` ASC) VISIBLE,
  INDEX `fk_agregado_por_idx` (`agregado_por` ASC) VISIBLE,
  INDEX `fk_proveedor_idx` (`proveedor` ASC) VISIBLE,
  INDEX `fk_ubicado_en_idx` (`ubicado_en` ASC) VISIBLE,
  CONSTRAINT `fk_agregado_por`
    FOREIGN KEY (`agregado_por`)
    REFERENCES `inventario_sena`.`empleados` (`id_empleado`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_proveedor`
    FOREIGN KEY (`proveedor`)
    REFERENCES `inventario_sena`.`proveedores` (`id_proveedores`),
  CONSTRAINT `fk_ubicado_en`
    FOREIGN KEY (`ubicado_en`)
    REFERENCES `inventario_sena`.`ubicacion_productos` (`id_ubicacion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario_sena`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_sena`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
